dist: trusty
language: python
python:
  - '3.6'
services:
  - mongodb
  - docker
before_install:
  - pip install codecov
  - pip install pipenv
install:
  - pipenv install --system
  - pipenv install --dev --system
before_script:
  - docker run -p 4569:4569 lphoward/fake-s3
script:
  - BLOG_TEST=TRUE pytest --cov blog.core tests
  - if [ "$TRAVIS_BRANCH" == "master" ]; then codecov; fi
