login:
  failed_login_timeout: 300
  max_failed_login: 5
  max_session_time: 43200
post:
  search_time_delay: 15
  view_time_delay: 3600
rules:
  comment:
    content_max_char: 124
    content_min_char: 10
  post:
    content_max_char: 10000
    content_min_char: 124
    title_max_char: 124
    title_min_char: 3
  user:
    name_max_char: 20
    name_min_char: 3
    password_max_char: 25
    password_min_char: 6
    username_max_char: 20
    username_min_char: 3
user:
  allow_avatar_capability: true
  allow_manual_registration: true
  require_email_verification: false
